# See: https://prettier.io/docs/en/configuration

printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
proseWrap: always
htmlWhitespaceSensitivity: css
endOfLine: lf
